# 应用名称
spring:
  application:
    name: micro-service-cloud-eureka-registration01

server:
  port: 7001  #该 Module 的端口号
eureka:
  instance:
    hostname: registration01 #eureka服务端的实例名称，
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://registration02:7002/eureka,http://registration03:7003/eureka #单机版服务注册中心