# 应用名称
spring:
  application:
    name: micro-service-cloud-ribbon-openfeign-consumer-user

server:
  port: 80 #端口号
############################################# Spring Cloud Ribbon 负载均衡配置##########################
eureka:
  client:
    register-with-eureka: true #本微服务为服务消费者，不需要将自己注册到服务注册中心
    fetch-registry: true  #本微服务为服务消费者，需要到服务注册中心搜索服务
    service-url:
      #服务注册中心集群
      defaultZone: http://registration01:7001/eureka,http://registration02:7002/eureka,http://registration03:7003/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）

ribbon:
  #建立连接所用的时间，适用于网络状况正常的情况下，两端两端连接所用的时间
  ReadTimeout: 6000
  #建立连接后，服务器读取到可用资源的时间
  ConnectionTimeout: 6000

feign:
  hystrix:
    enabled: true #开启客户端 hystrix

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
#    UserService#fallbackMethod():
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000